language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-head
bundler_args: --without development
before_script:
  - "rake db:reset RAILS_ENV=test"
script: "rspec"
notifications:
  irc:
    - "irc.freenode.org#belighted"
